; 2.77
(define *op-table* (make-equal-hash-table))
(define (put op type proc)
  (hash-table/put! *op-table* (list op type) proc))
(define (get op type)
  (hash-table/get *op-table* (list op type) '()))
(hash-table/clear! *op-table*)
(hash-table->alist *op-table*)

(define (attach-tag type-tag contents)
  (cons type-tag contents))
(define (type-tag datum) (car datum))
(define (contents datum) (cdr datum))
(define (apply-generic op . args)
  (let ((type-tags (map type-tag args)))
    (let ((proc (get op type-tags)))
      (if proc
	  (apply proc (map contents args))
	  (error "No method for types -- apply-generic" 
		 (list op type-tags))))))

(define (install-rectangular-package)
  (define (real-part z) (car z))
  (define (imag-part z) (cdr z))
  (define (make-from-real-imag x y) (cons x y))
  (define (magnitude z) (sqrt (+ (square (real-part z)) (square (imag-part z)))))
  (define (tag x) (attach-tag 'rectangular x))
  (put 'real-part '(rectangular) real-part)
  (put 'imag-part '(rectangular) imag-part)
  (put 'magnitude '(rectangular) magnitude)
  (put 'make-from-real-imag 'rectangular
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)
(install-rectangular-package)

(define (real-part z) (apply-generic 'real-part z))
(define (imag-part z) (apply-generic 'imag-part z))
(define (magnitude z) (apply-generic 'magnitude z))

(define (make-from-real-imag x y)
  ((get 'make-from-real-imag 'rectangular) x y))

(real-part (make-from-real-imag 3 4))
(magnitude (make-from-real-imag 3 4))

(define (install-complex-package)
  (define (make-from-real-imag x y)
    ((get 'make-from-real-imag 'rectangular) x y))
  (define (tag z) (attach-tag 'complex z))
  (define (equ? z1 z2)
    (and (= (real-part z1) (real-part z2)) 
	 (= (imag-part z1) (imag-part z2))))
  (define (=zero? z)
    (and (= 0 (real-part z))
	 (= 0 (imag-part z))))
  (put 'equ? '(complex complex)
       (lambda (z1 z2) 
	 (equ? z1 z2)))
  (put '=zero? '(complex)
       (lambda (z) (=zero? z)))
  (put 'make-from-real-imag 'complex 
       (lambda (x y) (tag (make-from-real-imag x y))))
  'done)
(install-complex-package)

(put 'real-part '(complex) real-part)
(put 'imag-part '(complex) imag-part)
(put 'magnitude '(complex) magnitude)
(put 'angle '(complex) magnitude)
  
(define (make-complex-from-real-imag x y)
  ((get 'make-from-real-imag 'complex) x y))

(magnitude (make-complex-from-real-imag 3 4))

; 2.78
(define (attach-tag type-tag contents)
  (cond ((number? contents) contents)
	(else (cons type-tag contents))))
(define (type-tag datum)
  (cond ((number? datum) 'scheme-number)
	((pair? datum) (car datum))
	(error "Bad tagged datum -- type-tag" datum)))
(define (contents datum)
  (cond ((number? datum) datum)
	((pair? datum) (cdr datum))
	(error "Bad tagged datum -- contents" datum)))

(define (add x y) (apply-generic 'add x y))
(define (sub x y) (apply-generic 'sub x y))
(define (mul x y) (apply-generic 'mul x y))
(define (div x y) (apply-generic 'div x y))

(define (install-scheme-number-package)
  (put 'add '(scheme-number scheme-number)
       (lambda (x y) (+ x y)))
  (put 'sub '(scheme-number scheme-number)
       (lambda (x y) (- x y)))
  (put 'mul '(scheme-number scheme-number)
       (lambda (x y) (* x y)))
  (put 'div '(scheme-number scheme-number)
       (lambda (x y) (/ x y)))
  (put 'equ? '(scheme-number scheme-number)
       (lambda (x y) (= x y)))
  (put '=zero? '(scheme-number)
       (lambda (x) (= 0 x)))
  (put 'make 'scheme-number
       (lambda (x) x))
  'done)
(install-scheme-number-package)
(=zero? 1)
(add 3 4)
(sub 5 6)
(mul 2 3)
(div 5 3)

; 2.79
(define (install-rational-package)
  (define (numer x) (car x))
  (define (denom x) (cdr x))
  (define (make-rat n d)
    (let ((g (gcd n d)))
      (cons (/ n g) (/ d g))))
  (define (equ? r1 r2)
    (and (= (numer r1) (numer r2))
	 (= (denom r1) (denom r2))))
  (define (=zero? r)
    (= 0 (numer r)))
  (put 'equ? '(rational rational)
    (lambda (r1 r2)
      (equ? r1 r2)))
  (put '=zero? '(rational)
       (lambda (r) (=zero? r)))
  (define (tag x) (attach-tag 'rational x))
  (put 'make 'rational
       (lambda (n d) (tag (make-rat n d))))
  'done)
(install-rational-package)
(define (make-rational n d)
  ((get 'make 'rational) n d))


(define (equ? x y) (apply-generic 'equ? x y))

(equ? (make-rational 3 2) (make-rational 3 3))
(equ? 4 4)
(equ? (make-complex-from-real-imag 3 1) (make-complex-from-real-imag 3 1))

; 2.80
(define (=zero? x) (apply-generic '=zero? x))
(=zero? (make-complex-from-real-imag 0 0))
(=zero? (make-rational 1 1))
(=zero? 0)
